### ISSUE TITLE
bot & top

### ISSUE THREAD

**Issue by pjqwudi** [5hadowblad3/Beacon_artifact#1]
Kudos to your work first!
I'm new to abstract interpretation. Recently, while reading the source code of beacon, I had doubts about the bottom and top attributes of the interval. What are the stages of analysis where the difference between the two is reflected?
```
    bool IsTop() const {
      unsigned w = getLB().getBitWidth();
      return getLB() == getMinVal(w, isSigned) && getUB() == getMaxVal(w, isSigned);
    }

    bool IsBot() const {
      return range_gt(getLB(), getUB(), isSigned);
    }
```
Looking forward to your reply!

**Comment by 5hadowblad3** [comment]
Hi there!

Thank you for being so interested in Beacon.

Top and bottom can be regarded as always false/true in terms of path condition. At a high-level view, It helps us determine whether the path is currently feasible during the backward analysis.

Moreover, for bounded disjunction, we do not need to consider those infeasible paths for merging.

I hope I have answered your question!
