### ISSUE TITLE
Cannot compile Ins: undefined variable

### ISSUE THREAD

**Issue by acidghost** [5hadowblad3/Beacon_artifact#3]
Hi, amazing work!

Unfortunately I `Ins` cannot be compiled because it's missing the definition of the `Byte` variable: https://github.com/5hadowblad3/Beacon_artifact/blob/749cc86a5d597b741212a731c68628a580770085/Ins/main.cpp#L537

**Comment by 5hadowblad3** [comment]
Hi,

I have updated the related setting, please have a look.

**Comment by acidghost** [comment]
Yes, that fixed it. Thanks!
