### ISSUE TITLE
How to use Beacon with ASAN?

### ISSUE THREAD

**Issue by Sisyphus-wang** [5hadowblad3/Beacon_artifact#8]
How do I enable ASAN in Beacon?

I think there are four possible places to set up ASAN:

There is an execution option -asan in Beacon/Ins, but it doesn't seem to have any effect.
Setting the environment variable export USE_AFL_ASAN=1 also doesn't work.
Adding -fsanitize=address to the final compilation environment doesn't work either.
If I add -fsanitize=address during the initial compilation, an error occurs in Beacon/precondInfer.

**Comment by 5hadowblad3** [comment]
A potential solution is to create two versions of the bc during the initial compilation. One is for precondInfer, and one is for final compilation.

Or, you can modify the [instrumentation code](https://github.com/5hadowblad3/Beacon_artifact/tree/master/Ins) to invoke the related instrumentation from compiler-rt.

**Comment by Sisyphus-wang** [comment]
Sorry, the -asan option for Beacon/Ins is working. The real reason for the failure was that the static analysis of precondInfer did not find the exact call chain. So when I changed to another target program, I was able to successfully use AddressSanitizer with beacon
